In [1]:
import numpy as np

In [6]:
data=np.array([2,4,4],[3,5,5])
data

TypeError: Field elements must be 2- or 3-tuples, got '3'

In [12]:
data1=np.random.randn(3, 11)
data1

array([[-0.85060666, -1.998552  , -0.65650097, -1.52148998, -0.37110672,
        -0.6097062 , -1.01424023, -0.2283809 , -0.00432877, -0.94620946,
         0.25097154],
       [-0.28586967, -0.17708679, -0.17959909, -0.48654125, -0.73545285,
         0.11090758, -0.69713055, -0.99916848, -0.32059034,  0.13658098,
        -0.34322079],
       [-0.33002172, -0.18806116,  1.33883078, -0.0917898 ,  0.89448109,
        -0.01910009,  0.4822464 ,  0.89709146, -0.38835875, -0.08547827,
        -0.98153272]])

In [18]:
data1.ndim
data1+10
data1.shape
data1.dtype

dtype('float64')

In [22]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [25]:
float_arr = arr1.astype(np.float64)
print(arr1.dtype)
float_arr
float_arr.dtype

float64


dtype('float64')

In [37]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([980444020, 842084143, 774909495, 976301616, 842478645,        51,
               0,         1], dtype=uint32)

In [38]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr[5:8]

array([5, 6, 7])

In [41]:
arr[5]=4
arr

array([0, 1, 2, 3, 4, 4, 6, 7, 8, 9])

In [43]:
arr_slice=arr[5:8]
arr_slice[1]=123
arr

array([  0,   1,   2,   3,   4,   4, 123,   7,   8,   9])

In [46]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[:1,:2]

array([[1, 2]])

In [51]:
arr = np.empty((8, 4))
for i in range(7):
    arr[i]=i
arr

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [1.00000000e+000, 1.00000000e+000, 1.00000000e+000,
        1.00000000e+000],
       [2.00000000e+000, 2.00000000e+000, 2.00000000e+000,
        2.00000000e+000],
       [3.00000000e+000, 3.00000000e+000, 3.00000000e+000,
        3.00000000e+000],
       [4.00000000e+000, 4.00000000e+000, 4.00000000e+000,
        4.00000000e+000],
       [5.00000000e+000, 5.00000000e+000, 5.00000000e+000,
        5.00000000e+000],
       [6.00000000e+000, 6.00000000e+000, 6.00000000e+000,
        6.00000000e+000],
       [9.79094970e-307, 1.78019354e-306, 1.69120552e-306,
        2.56765117e-312]])

In [52]:
arr[[1,4,6,5]]

array([[1., 1., 1., 1.],
       [4., 4., 4., 4.],
       [6., 6., 6., 6.],
       [5., 5., 5., 5.]])

In [53]:
arr.T

array([[0.00000000e+000, 1.00000000e+000, 2.00000000e+000,
        3.00000000e+000, 4.00000000e+000, 5.00000000e+000,
        6.00000000e+000, 9.79094970e-307],
       [0.00000000e+000, 1.00000000e+000, 2.00000000e+000,
        3.00000000e+000, 4.00000000e+000, 5.00000000e+000,
        6.00000000e+000, 1.78019354e-306],
       [0.00000000e+000, 1.00000000e+000, 2.00000000e+000,
        3.00000000e+000, 4.00000000e+000, 5.00000000e+000,
        6.00000000e+000, 1.69120552e-306],
       [0.00000000e+000, 1.00000000e+000, 2.00000000e+000,
        3.00000000e+000, 4.00000000e+000, 5.00000000e+000,
        6.00000000e+000, 2.56765117e-312]])

In [55]:
arr.swapaxes(1,2)

AxisError: axis2: axis 2 is out of bounds for array of dimension 2

In [1]:
from matplotlib import pyplot as plt
from

SyntaxError: invalid syntax (<ipython-input-1-0feac8f57033>, line 2)

In [3]:
for i in '':
    print(i)

In [4]:
for i in range(11,15,3):
    print(i)

11
14


In [6]:
a=dict()
a[1]

KeyError: 1

In [1]:
import pandas as pd

In [3]:
fd=pd.read_csv('data.csv')

In [4]:
fd.head()

ID  Clump_Thickness  Cell_Size_Uniformity  Cell_Shape_Uniformity  \
0  1000025                5                     1                      1   
1  1002945                5                     4                      4   
2  1015425                3                     1                      1   
3  1016277                6                     8                      8   
4  1017023                4                     1                      1   

   Marginal_Adhesion  Single_Epithelial_Cell_Size Bare_Nuclei  \
0                  1                          2.0           1   
1                  5                          NaN          10   
2                  1                          2.0           2   
3                  1                          3.0           4   
4                  3                          2.0           1   

   Bland_Chromatin  Normal_Nucleoli  Mitoses  Cancer_Type  
0                3                1        1            2  
1                3                2        1            2  
2                3                1        1            2  
3                3                7        1            2  
4                3                1        1            2

In [5]:
fd.column['Cell_Size_Uniformity']

AttributeError: 'DataFrame' object has no attribute 'column'

In [9]:
fd[['Cell_Size_Uniformity','Cell_Shape_Uniformity','Bare_Nuclei']]

Cell_Size_Uniformity  Cell_Shape_Uniformity Bare_Nuclei
0                       1                      1           1
1                       4                      4          10
2                       1                      1           2
3                       8                      8           4
4                       1                      1           1
..                    ...                    ...         ...
694                     1                      1           2
695                     1                      1           1
696                    10                     10           3
697                     8                      6           4
698                     8                      8           5

[699 rows x 3 columns]

In [10]:
fa=pd.read_csv('index.csv')

In [11]:
fa['C'] #column

0       8
1       0
2       0
3       0
4       0
       ..
252     0
253     6
254     0
255    45
256     6
Name: C, Length: 257, dtype: int64

In [14]:
fa[['K','L']] #rows and column

K  L
0    0  3
1    0  3
2    0  3
3    0  3
4    0  3
..  .. ..
252  0  3
253  0  3
254  0  3
255  0  3
256  0  3

[257 rows x 2 columns]

In [16]:
fa.iloc[0:5,0:2]

A  B
0  C  A
1  C  R
2  C  R
3  C  A
4  C  A

In [17]:
import numpy as np

In [18]:
fe=pd.read_csv('bigmart_data')

FileNotFoundError: [Errno 2] No such file or directory: 'bigmart_data'

In [23]:
import numpy as np
import pandas as pd
fe=pd.read_csv('bigmart_data.csv')
fe.head()

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0           FDA15         9.30          Low Fat         0.016047   
1           DRC01         5.92          Regular         0.019278   
2           FDN15        17.50          Low Fat         0.016760   
3           FDX07        19.20          Regular         0.000000   
4           NCD19         8.93          Low Fat         0.000000   

               Item_Type  Item_MRP Outlet_Identifier  \
0                  Dairy  249.8092            OUT049   
1            Soft Drinks   48.2692            OUT018   
2                   Meat  141.6180            OUT049   
3  Fruits and Vegetables  182.0950            OUT010   
4              Household   53.8614            OUT013   

   Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                       1999      Medium               Tier 1   
1                       2009      Medium               Tier 3   
2                       1999      Medium               Tier 1   
3                       1998         NaN               Tier 3   
4                       1987        High               Tier 3   

         Outlet_Type  Item_Outlet_Sales  
0  Supermarket Type1          3735.1380  
1  Supermarket Type2           443.4228  
2  Supermarket Type1          2097.2700  
3      Grocery Store           732.3800  
4  Supermarket Type1           994.7052

In [22]:
fe=fe.dropna(how='any')

In [32]:
#data_sort=fe.sort_values(by='Outlet_Establishment_Year')sort by index
fe.sort_values(by='Outlet_Establishment_Year',ascending=False,inplace=True)
fe[:5]

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
5371           FDC11       20.500          Low Fat         0.142370   
8440           NCO29       11.150          Low Fat         0.032388   
5472           FDQ14        9.270          Low Fat         0.062039   
3778           FDZ36        6.035          Regular         0.066052   
7456           NCK31       10.895          Low Fat         0.027158   

               Item_Type  Item_MRP Outlet_Identifier  \
5371       Starchy Foods   90.6172            OUT018   
8440  Health and Hygiene  164.3526            OUT018   
5472               Dairy  148.0050            OUT018   
3778        Baking Goods  187.7240            OUT018   
7456              Others   50.2666            OUT018   

      Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
5371                       2009      Medium               Tier 3   
8440                       2009      Medium               Tier 3   
5472                       2009      Medium               Tier 3   
3778                       2009      Medium               Tier 3   
7456                       2009      Medium               Tier 3   

            Outlet_Type  Item_Outlet_Sales  
5371  Supermarket Type2          1427.4752  
8440  Supermarket Type2          2960.1468  
5472  Supermarket Type2          1797.6600  
3778  Supermarket Type2          2050.6640  
7456  Supermarket Type2           820.2656

In [34]:
fe.sort_index(inplace=True)
fe[:5]

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0           FDA15         9.30          Low Fat         0.016047   
1           DRC01         5.92          Regular         0.019278   
2           FDN15        17.50          Low Fat         0.016760   
3           FDX07        19.20          Regular         0.000000   
4           NCD19         8.93          Low Fat         0.000000   

               Item_Type  Item_MRP Outlet_Identifier  \
0                  Dairy  249.8092            OUT049   
1            Soft Drinks   48.2692            OUT018   
2                   Meat  141.6180            OUT049   
3  Fruits and Vegetables  182.0950            OUT010   
4              Household   53.8614            OUT013   

   Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                       1999      Medium               Tier 1   
1                       2009      Medium               Tier 3   
2                       1999      Medium               Tier 1   
3                       1998         NaN               Tier 3   
4                       1987        High               Tier 3   

         Outlet_Type  Item_Outlet_Sales  
0  Supermarket Type1          3735.1380  
1  Supermarket Type2           443.4228  
2  Supermarket Type1          2097.2700  
3      Grocery Store           732.3800  
4  Supermarket Type1           994.7052

In [36]:
import numpy as np
import pandas as pd
df1=pd.DataFrame({'A':['A0','A1','A2'],
                 'B':['B0','B1','B2'],
                 'C':['C0','C1','C2']},
                index=[0,1,2])
df2=pd.DataFrame({'A':['A3','A4','A5'],
                 'B':['B3','B4','B5'],
                 'C':['C3','C4','C5']},
                index=[3,4,5])
df3=pd.DataFrame({'A':['A6','A7','A8'],
                 'B':['B6','B7','B8'],
                 'C':['C6','C7','C8']},
                index=[6,7,8])

In [40]:
#m1=pd.concat([df1,df2,df3])
m1=pd.concat([df1,df2,df3],keys=['x','y','z'])
m1

A   B   C
x 0  A0  B0  C0
  1  A1  B1  C1
  2  A2  B2  C2
y 3  A3  B3  C3
  4  A4  B4  C4
  5  A5  B5  C5
z 6  A6  B6  C6
  7  A7  B7  C7
  8  A8  B8  C8

In [41]:
m1.loc['y']

A   B   C
3  A3  B3  C3
4  A4  B4  C4
5  A5  B5  C5

In [46]:
df4=pd.DataFrame({'B':['B2','B3','B6'],
                 
                 'C':['C2','C3','C6'],
                 'F':['F2','F3','F6'],},
                index=[2,3,6])
m2=pd.concat([df1,df4],axis=1,join='inner')#sort=False),
m2

A   B   C   B   C   F
2  A2  B2  C2  B2  C2  F2

In [47]:
m2=pd.concat([df1,df4],axis=1,join='outer')
m2

A    B    C    B    C    F
0   A0   B0   C0  NaN  NaN  NaN
1   A1   B1   C1  NaN  NaN  NaN
2   A2   B2   C2   B2   C2   F2
3  NaN  NaN  NaN   B3   C3   F3
6  NaN  NaN  NaN   B6   C6   F6

In [53]:
df_1=pd.DataFrame({'id':['1','2','3'],
    'f_name':['aby','amy','any'],
    'l_name':['kebab','prawn','fish']
                  })
df_2=pd.DataFrame({'id':['4','5','6'],
    'f_name':['baby','bamy','bany'],
    'l_name':['bebab','brawn','bish']
                  })
df_3=pd.DataFrame({'id':['1','2','3','4','5','6','7','8','9','10','11'],'test_id':[51,15,15,61,14,1,16,14,12,14,13,12]
                  })

ValueError: arrays must all be same length

In [55]:
#m3=pd.merge(df_1,df_3,on='id')
m3=pd.merge(df_1,df_2,on='id',how='outer')
m3=pd.merge(df_1,df_2,on='id',how='inner')
m3=pd.merge(df_1,df_2,on='id',how='right') #shows complete data of right array
m3=pd.merge(df_1,df_2,on='id',how='left')
m3

id f_name_x l_name_x f_name_y l_name_y
0  1      aby    kebab      NaN      NaN
1  2      amy    prawn      NaN      NaN
2  3      any     fish      NaN      NaN
3  4      NaN      NaN     baby    bebab
4  5      NaN      NaN     bamy    brawn
5  6      NaN      NaN     bany     bish

In [56]:
import numpy as np
import pandas as pd
fe=pd.read_csv('bigmart_data.csv')
fe.head()

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0           FDA15         9.30          Low Fat         0.016047   
1           DRC01         5.92          Regular         0.019278   
2           FDN15        17.50          Low Fat         0.016760   
3           FDX07        19.20          Regular         0.000000   
4           NCD19         8.93          Low Fat         0.000000   

               Item_Type  Item_MRP Outlet_Identifier  \
0                  Dairy  249.8092            OUT049   
1            Soft Drinks   48.2692            OUT018   
2                   Meat  141.6180            OUT049   
3  Fruits and Vegetables  182.0950            OUT010   
4              Household   53.8614            OUT013   

   Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                       1999      Medium               Tier 1   
1                       2009      Medium               Tier 3   
2                       1999      Medium               Tier 1   
3                       1998         NaN               Tier 3   
4                       1987        High               Tier 3   

         Outlet_Type  Item_Outlet_Sales  
0  Supermarket Type1          3735.1380  
1  Supermarket Type2           443.4228  
2  Supermarket Type1          2097.2700  
3      Grocery Store           732.3800  
4  Supermarket Type1           994.7052

In [57]:
fe.apply(lambda x:x)#the lambda function is used to dataa maniipulate and it also used insteadof "for " for iterati0n

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0              FDA15        9.300          Low Fat         0.016047   
1              DRC01        5.920          Regular         0.019278   
2              FDN15       17.500          Low Fat         0.016760   
3              FDX07       19.200          Regular         0.000000   
4              NCD19        8.930          Low Fat         0.000000   
...              ...          ...              ...              ...   
8518           FDF22        6.865          Low Fat         0.056783   
8519           FDS36        8.380          Regular         0.046982   
8520           NCJ29       10.600          Low Fat         0.035186   
8521           FDN46        7.210          Regular         0.145221   
8522           DRG01       14.800          Low Fat         0.044878   

                  Item_Type  Item_MRP Outlet_Identifier  \
0                     Dairy  249.8092            OUT049   
1               Soft Drinks   48.2692            OUT018   
2                      Meat  141.6180            OUT049   
3     Fruits and Vegetables  182.0950            OUT010   
4                 Household   53.8614            OUT013   
...                     ...       ...               ...   
8518            Snack Foods  214.5218            OUT013   
8519           Baking Goods  108.1570            OUT045   
8520     Health and Hygiene   85.1224            OUT035   
8521            Snack Foods  103.1332            OUT018   
8522            Soft Drinks   75.4670            OUT046   

      Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                          1999      Medium               Tier 1   
1                          2009      Medium               Tier 3   
2                          1999      Medium               Tier 1   
3                          1998         NaN               Tier 3   
4                          1987        High               Tier 3   
...                         ...         ...                  ...   
8518                       1987        High               Tier 3   
8519                       2002         NaN               Tier 2   
8520                       2004       Small               Tier 2   
8521                       2009      Medium               Tier 3   
8522                       1997       Small               Tier 1   

            Outlet_Type  Item_Outlet_Sales  
0     Supermarket Type1          3735.1380  
1     Supermarket Type2           443.4228  
2     Supermarket Type1          2097.2700  
3         Grocery Store           732.3800  
4     Supermarket Type1           994.7052  
...                 ...                ...  
8518  Supermarket Type1          2778.3834  
8519  Supermarket Type1           549.2850  
8520  Supermarket Type1          1193.1136  
8521  Supermarket Type2          1845.5976  
8522  Supermarket Type1           765.6700  

[8523 rows x 12 columns]

In [60]:
fe.apply(lambda x:x[0]) #access first row
fe.apply(lambda x:x[0],axis=1) #first column
fe.apply(lambda x:x["Item_Type"],axis=1) 

0                       Dairy
1                 Soft Drinks
2                        Meat
3       Fruits and Vegetables
4                   Household
                ...          
8518              Snack Foods
8519             Baking Goods
8520       Health and Hygiene
8521              Snack Foods
8522              Soft Drinks
Length: 8523, dtype: object

In [64]:
def chan(price):
    if price>200:
        price=200
    return price
#
fe["Item_MRP"].apply(lambda x:chan(x))[:5]

0    200.0000
1     48.2692
2    141.6180
3    182.0950
4     53.8614
Name: Item_MRP, dtype: float64

In [75]:
def chang(city):
    if city=='Tier 1':
        label=0
    elif city=='Tier 2':
        label=1
    else:
        label=3
    return label
        
fe["Outlet_Location_Type"]=fe["Outlet_Location_Type"].apply(chang)
fe

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0              FDA15        9.300          Low Fat         0.016047   
1              DRC01        5.920          Regular         0.019278   
2              FDN15       17.500          Low Fat         0.016760   
3              FDX07       19.200          Regular         0.000000   
4              NCD19        8.930          Low Fat         0.000000   
...              ...          ...              ...              ...   
8518           FDF22        6.865          Low Fat         0.056783   
8519           FDS36        8.380          Regular         0.046982   
8520           NCJ29       10.600          Low Fat         0.035186   
8521           FDN46        7.210          Regular         0.145221   
8522           DRG01       14.800          Low Fat         0.044878   

                  Item_Type  Item_MRP Outlet_Identifier  \
0                     Dairy  249.8092            OUT049   
1               Soft Drinks   48.2692            OUT018   
2                      Meat  141.6180            OUT049   
3     Fruits and Vegetables  182.0950            OUT010   
4                 Household   53.8614            OUT013   
...                     ...       ...               ...   
8518            Snack Foods  214.5218            OUT013   
8519           Baking Goods  108.1570            OUT045   
8520     Health and Hygiene   85.1224            OUT035   
8521            Snack Foods  103.1332            OUT018   
8522            Soft Drinks   75.4670            OUT046   

      Outlet_Establishment_Year Outlet_Size  Outlet_Location_Type  \
0                          1999      Medium                     3   
1                          2009      Medium                     3   
2                          1999      Medium                     3   
3                          1998         NaN                     3   
4                          1987        High                     3   
...                         ...         ...                   ...   
8518                       1987        High                     3   
8519                       2002         NaN                     3   
8520                       2004       Small                     3   
8521                       2009      Medium                     3   
8522                       1997       Small                     3   

            Outlet_Type  Item_Outlet_Sales  
0     Supermarket Type1          3735.1380  
1     Supermarket Type2           443.4228  
2     Supermarket Type1          2097.2700  
3         Grocery Store           732.3800  
4     Supermarket Type1           994.7052  
...                 ...                ...  
8518  Supermarket Type1          2778.3834  
8519  Supermarket Type1           549.2850  
8520  Supermarket Type1          1193.1136  
8521  Supermarket Type2          1845.5976  
8522  Supermarket Type1           765.6700  

[8523 rows x 12 columns]

In [1]:
import re

In [2]:
import re

#match a word at the beginning of a string

result = re.match('Analytics',r'Analytics Vidhya is the largest data science community of India') 
print(result)

result_2 = re.match('largest',r'Analytics Vidhya is the largest data science community of India') 
print(result_2)

<re.Match object; span=(0, 9), match='Analytics'>
None


In [3]:
print(result.group())

Analytics


In [4]:
result = re.search('founded',r'Andrew NG founded Coursera. He also founded deeplearning.ai')
print(result.group())

founded


In [6]:
str = r'Analytics Vidhya is the largest data science community of India'
x=re.findall("\AAnalytics",str)
print(x)

['Analytics']


In [11]:
x = re.findall(r"est\b", str)
print(x)

['est']


In [12]:
x = re.findall(r"\Ben", str)

print(x)

['en']


In [15]:
str = "22 million monthly visits in Jan'19."

#Check if the string contains any digits (numbers from 0-9):
x = re.findall("\d", str)

print(x)

if (x):
  print("Yes, there is at least one match!")
else:
  print("No match")

['2', '2', '1', '9']
Yes, there is at least one match!


In [17]:
str = "rohan and rohit recently published a research paper!" 

#Search for a string that starts with "ro", followed by three (any) characters

x = re.findall("an.", str)
x2 = re.findall("ro...", str)
print(x)

['an ', 'and']
